### ISSUE TITLE
Possible Flaw - Bypassing the Original Model Through Python and LLM Filters

### ISSUE THREAD

**Issue by regoar** [ethz-spylab/satml-llms-ctf-issues#13]
I believe I've spotted a problem in the rules of the competition. By utilizing the Python filter to gather chat history and then transferring it to the LLM filter, competitors can effectively bypass completely the initial model. This results in interactions with the LLM-filter that remain oblivious to the 'secret'.

**Comment by dedeswim** [comment]
I'm not sure I understand. Can you please give a concrete example?

**Comment by regoar** [comment]
1.  The Python-filter comes first and turn the chat history list parameter into one 'long' string containing the whole chat history, then return that string.

2. The LLM-filter is basically just "{model_output}" - meaning after substitution the LLM-filter input is just the complete chat so far, since {model_output} is the output described in (1).

With those filters in place you are basically having a talk with an LLM-filter that receive each time the compiled chat in one message and output the next response accordingly. Since I assume the LLM-filter does not have the hidden preamble its seems pretty much like talking to the original LLM without the secret.

At least that the situation as far as i understood it, sorry for the bother if i misunderstood.

**Comment by dedeswim** [comment]
If I understand correctly, what you suggest would be: have a Python filter that returns the full conversation as a string with some specific formatting, instead of a filtered version of the last generation, and then pass this to the LLM filter to run the generation of the next message?

**Comment by regoar** [comment]
Yes, I've tried it, including with the evaluate utility, and it works fine. Naturally, it can't reveal the 'secret' because it doesn't know it.

I was wondering if you intended for competitors to simply overlook this option, or if they should also overlook the more general option of using more parts of the conversation in the LLM filter?

**Comment by dedeswim** [comment]
Hi all! Thanks a lot for contributing to the discussion. As pointed out by @s-zanella, these defences fall within "hacking", are outside the scope of the competition, and we thus do not consider them as valid. We added some clarifications and guidelines in Section 7 of the rules on our website, and we will send a message on the Google Group.

We are sorry about the ambiguity and for the oversight on our side. If we will run the competition again in a future edition, we will make the filters output a boolean acceptance/rejection of user prompts and model outputs. However, we believe that this would be too big of a change to do at this stage of the competition for the current edition.

Please let us know if this clarifies your doubts, otherwise we'll close the issue in a week.
