### ISSUE TITLE
Is the secret alphanumeric or not?

### ISSUE THREAD

**Issue by epistoteles** [ethz-spylab/satml-llms-ctf-issues#29]
In the rules, the secret is described as alphanumeric.

However, in the API docs, the secret is also instantiated to be something else, e.g. 's]]]]]':

<img src="https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/20706203/98d91435-e608-43ae-b93f-02db7abc3e3e" width="500">

For me alphanumeric means a-zA-Z0-9, and nothing else. This is important for my Python filter. Could you please clarify?

**Comment by Jordine** [comment]
Also, will the secrets all be strictly 6 characters long? I can't set it to anything longer in the interface.

**Comment by epistoteles** [comment]
Edit: It looks like this is some serious failure in the backend. No matter what secret I put in the chat API, the <secret> is always 's]]]]]' for the model and all filters.

**Comment by dedeswim** [comment]
Hi @epistoteles can you please tell me the steps to reproduce this? Where do you see what the secret is once the conversation is instantiated?

**Comment by epistoteles** [comment]
@dedeswim The simplest way to see the secret after instantiation is to use `return model_output + secret` as your Python "filter". I am also able to consistently extract my own dummy system prompt, which seems to contains 's]]]]]' where the secret should be.

**Comment by dedeswim** [comment]
Hi thanks for reporting that you're not having the issue anymore. Just so you know, we didn't make any changes on our end.

As per your question from above, the secret will be composed of exactly 6 alphanumeric characters.

**Comment by KrystofM** [comment]
I am having the same issue in the example of the secret within the SwaggerUI, only generating strings with first character being random and the rest being ]]]]]:

<img width="315" alt="Screenshot 2024-01-17 at 11 00 51 AM" src="https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/23424878/055e9084-2e3a-42bf-bb43-41b86743c0eb">

This could be just a problem of Swagger, however. Anyway it would nice to specify alphanumeric properly as I don't think the definition is stable; for me it meant english *only* uppercase A-Z (26) and 0-9 (10). In case is it either [a-zA-Z0-9] or [A-Z0-9] it would be nice to change that specification in the OpenAPI documentation, instead of leaving [[::ascii::]]{6}, which is a much larger set of characters. I would also suggest possibly leaving out the minLength and maxLength fields and instead just using the start and endline regex tokens ^$ to have an exact match.

```
{
      "type":"string",
      "pattern":"^[a-zA-Z0-9]{6}$",
      "title":"Secret"
}
```
or

```
{
      "type":"string",
      "pattern":"^[A-Z0-9]{6}$",
      "title":"Secret"
}
```

**Comment by dedeswim** [comment]
Hi, we'll change the OpenAPI specification ASAP to make sure things are clear.

In any case, we confirm that the secrets are going to be only alphanumeric characters, where the letters can be both lowercase and uppercase.

**Comment by dedeswim** [comment]
Done!
